import './globals.css'
import type { Metadata } from 'next'
import { I18nProviderClient } from '../../locales/client'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <I18nProviderClient>
      {children}
    </I18nProviderClient>
  )
}
